Sigma_1_0_0.md
wip/Sigma_2_0_0.md

Small typo and markdown fixes to the specs

Update Sigma Specs

---

Filename_sigmahq.md
Sigma_1_0_0.md
wip/Sigma_2_0_0.md

Add information about the filename

Filename information

---

README.md
Sigma_1_0_1.md
wip/Sigma_2_0_0.md

Add String Wildcard section

---

sigmahq/Sigmahq_filename_rule.md

Add and order missing service name for sigmaHQ file

Add service name

---

Taxonomy_specification.md

Add Github product as introduced in [PR#3942](https://github.com/SigmaHQ/sigma/pull/3942)

feat: add github product

---

sigmahq/sigmahq_conventions.md

This PR adds new recommendations to mitigate errors seen in recent PRs provided by new contributors.

feat: update sigmahq_conventions.md

---

appendix_modifer.md

Reworks of the appendix_modifer file

Update appendix_modifer.md to PySigma 0.7.6

---

appendix_meta_rules.md

- Add "generate" field
- Change to filter
- Small fix
Need review.

Appendix_meta_rules fast review

---

Tags_specification.md

Add tag detection

---

Sigma_specification.md

Just add more information for the multiple conditions use

Complete the information for multiple conditions

---

sigmahq/sigmahq_title_rule.md

Adds help for writing rule titles in SigmaHQ

sigmahq title first draft

---

Tags_specification.md

Integration of "Summiting the Pyramid" scheme from MITRE.

Added stp tag namespace

---

README.md
Sigma_meta_filter.md
Sigma_meta_rules.md
V2_changes.md
schema/meta-filter-schema.json

- Split Meta Rule and Meta Filter
- Add schema/meta-filter-schema.json
- Update readme

Add Meta filter

---

Sigma_meta_rules.md
Sigma_specification.md

- Add missing information about Keywords search
- Fix value_count example

Small update

---

Sigma_meta_rules.md
schema/detection-rule-schema.json
schema/meta-rule-schema.json

Small updates:
- Update detection-rule-schema.json to V2
- Update meta-rule-schema.json to V2
- Update Sigma_meta_rules.md with missing optional fields
- Order Sigma_meta_rules.md to better see fields under correlation section
check-jsonschema succeeds, although I don't know why 😄

Update V2 Schema

---

Sigma_specification.md

As understanding the logsource is always complicated, I have reworked the section.

Update Logsource Section

---

other/version-2-changes.md

Fix the uri used to point the Sigma Modifiers Appendix file

Minor fix in spec changes

---

specification/sigma-correlation-rules-specification.md

Add precission following the number of questions on discord

Add precission to group-by

---

appendix/sigma-taxonomy-appendix.md

Add the service as the rules are already on sigmaHQ
close #154

Add service iis-configuration

---

specification/sigma-correlation-rules-specification.md

Add the missing `Requires` information for temporal rules

Add requires for temporal

---

appendix/sigma-tags-appendix.md

Add the "defenses" section of the [MITRE](https://attack.mitre.org/)

Add MITRE attack defenses section tag

---

.github/workflows/lint.yml
README.md
appendix/sigma-modifiers-appendix.md
appendix/sigma-tags-appendix.md
appendix/sigma-taxonomy-appendix.md
other/version-2-changes.md
requirements.txt
sigmahq/sigmahq-filename-convention.md
sigmahq/sigmahq-rule-convention.md
sigmahq/sigmahq-title-convention.md
specification/sigma-correlation-rules-specification.md
specification/sigma-filters-specification.md
specification/sigma-rules-specification.md

Small change : 
- Use of mdformat and mdformat-toc
- Add a workflow with mdformat  check

Add a markdown Linter

---

json-schema/sigma-correlation-rules-schema.json
specification/sigma-correlation-rules-specification.md

From an old discussion on discord about the lack of a metric operator in correlation.
Add the operators:
- sum
- max
- min
- average
- percentile

Metric operator in correlation

---

.github/workflows/check-format.yml
json-schema/sigma-correlation-rules-schema.json
json-schema/sigma-detection-rule-schema.json
json-schema/sigma-filters-schema.json

Use bione to lint and check the json schema

ci: 🤖 Check json formatting with biome

---

README.md
json-schema/sigma-correlation-rules-schema.json
json-schema/sigma-filters-schema.json
specification/sigma-appendix-custom-taxonomy.md
specification/sigma-correlation-rules-specification.md
specification/sigma-filters-specification.md
specification/sigma-rules-specification.md
tests/correlation/event_count_ecs.yml
tests/filter/filter_ecs.yml
tests/rules/rule_ecs.yml

- Add generic network logsource
- Add missing `taxonomy` for correlation and filter
close #46 
close #169

Add Generic network logsource

---

specification/sigma-appendix-modifiers.md
specification/sigma-appendix-tags.md
specification/sigma-appendix-taxonomy.md
specification/sigma-correlation-rules-specification.md
specification/sigma-filters-specification.md
specification/sigma-rules-specification.md

- Add `neq` to `fieldref`
- Add `correlation` to related
- Udpate history section
close #136 
close #102

Fix old issue
